Resources:
  usersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.USER_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  productTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.PRODUCT_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: provider
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: providerIndex
          KeySchema:
            - AttributeName: provider
              KeyType: HASH
          Projection:
            ProjectionType: 'ALL'
      BillingMode: PAY_PER_REQUEST
  subscriptionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.SUBSCRIPTION_TABLE}
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: productId
              KeyType: RANGE
          Projection:
            ProjectionType: 'ALL'
      BillingMode: PAY_PER_REQUEST