server:
  port: 9090
spring:
  data:
    mongodb:
      database: wishbooks
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-hw-jobs-integration.eu.auth0.com/.well-known/jwks.json
