Resources:
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: "https-only"
              OriginReadTimeout: 30
              OriginSSLProtocols:
                - "TLSv1.2"
            DomainName: "nefyt675s4.execute-api.eu-central-1.amazonaws.com"
            Id: "api"
            OriginPath: ""
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            DomainName: "${self:custom.bucketName}.s3.eu-central-1.amazonaws.com"
            Id: "s3"
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity: ""
        OriginGroups:
          Quantity: 0
        DefaultCacheBehavior:
          AllowedMethods:
            - "HEAD"
            - "GET"
          CachedMethods:
            - "HEAD"
            - "GET"
          Compress: true
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
          SmoothStreaming: false
          TargetOriginId: "s3"
          ViewerProtocolPolicy: "allow-all"
        CacheBehaviors:
          - AllowedMethods:
              - "HEAD"
              - "DELETE"
              - "POST"
              - "GET"
              - "OPTIONS"
              - "PUT"
              - "PATCH"
            Compress: true
            CachePolicyId: "c3e44aee-b2c4-4a53-a3f1-b5a5732a36e8"
            PathPattern: "/api/*"
            SmoothStreaming: false
            TargetOriginId: "api"
            ViewerProtocolPolicy: "https-only"
        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: "/index.html"
            ResponseCode: "200"
            ErrorCachingMinTTL: 10
        PriceClass: "PriceClass_100"
        Enabled: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: "TLSv1"
        Restrictions:
          GeoRestriction:
            RestrictionType: "none"
        HttpVersion: "http2"
        DefaultRootObject: "index.html"
        IPV6Enabled: true
