AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    CloudFrontCloudFrontOriginAccessIdentity:
        Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
        Properties:
            CloudFrontOriginAccessIdentityConfig: 
                Comment: "access-identity-nw-profile-images-spike-20191203.s3.amazonaws.com"

    CloudFrontDistribution:
        Type: "AWS::CloudFront::Distribution"
        Properties:
            DistributionConfig: 
                Origins: 
                  - 
                    ConnectionAttempts: 3
                    ConnectionTimeout: 10
                    CustomOriginConfig: 
                        HTTPPort: 80
                        HTTPSPort: 443
                        OriginKeepaliveTimeout: 5
                        OriginProtocolPolicy: "https-only"
                        OriginReadTimeout: 30
                        OriginSSLProtocols: 
                          - "TLSv1.2"
                    DomainName: "42p84bzsld.execute-api.eu-central-1.amazonaws.com"
                    Id: "42p84bzsld.execute-api.eu-central-1.amazonaws.com"
                    OriginPath: ""
                  - 
                    ConnectionAttempts: 3
                    ConnectionTimeout: 10
                    DomainName: "hw-jobs-integration-product-checker.s3.eu-central-1.amazonaws.com"
                    Id: "hw-jobs-integration-product-checker.s3.eu-central-1.amazonaws.com"
                    OriginPath: ""
                    S3OriginConfig: 
                        OriginAccessIdentity: ""
                OriginGroups: 
                    Quantity: 0
                DefaultCacheBehavior: 
                    AllowedMethods: 
                      - "HEAD"
                      - "GET"
                    CachedMethods: 
                      - "HEAD"
                      - "GET"
                    Compress: true
                    CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
                    SmoothStreaming: false
                    TargetOriginId: "hw-jobs-integration-product-checker.s3.eu-central-1.amazonaws.com"
                    ViewerProtocolPolicy: "allow-all"
                CacheBehaviors: 
                  - 
                    AllowedMethods: 
                      - "HEAD"
                      - "DELETE"
                      - "POST"
                      - "GET"
                      - "OPTIONS"
                      - "PUT"
                      - "PATCH"
                    Compress: true
                    CachePolicyId: "9448adfc-7846-4d1e-8b89-5a5317fcd32e"
                    PathPattern: "/api/*"
                    SmoothStreaming: false
                    TargetOriginId: "42p84bzsld.execute-api.eu-central-1.amazonaws.com"
                    ViewerProtocolPolicy: "https-only"
                CustomErrorResponses: 
                  - 
                    ErrorCode: 404
                    ResponsePagePath: "/index.html"
                    ResponseCode: "200"
                    ErrorCachingMinTTL: 10
                Comment: ""
                PriceClass: "PriceClass_100"
                Enabled: true
                ViewerCertificate: 
                    CloudFrontDefaultCertificate: true
                    MinimumProtocolVersion: "TLSv1"
                Restrictions: 
                    GeoRestriction: 
                        RestrictionType: "none"
                HttpVersion: "http2"
                DefaultRootObject: "index.html"
                IPV6Enabled: true

    CloudFrontCachePolicy:
        Type: "AWS::CloudFront::CachePolicy"
        Properties:
            CachePolicyConfig: 
                Name: "NoCachePlusAuthorization"
                Comment: "Created through dialog"
                DefaultTTL: 0
                MaxTTL: 1
                MinTTL: 0
                ParametersInCacheKeyAndForwardedToOrigin: 
                    EnableAcceptEncodingGzip: true
                    EnableAcceptEncodingBrotli: true
                    CookiesConfig: {}
                    HeadersConfig: 
                        HeaderBehavior: "whitelist"
                        Headers: 
                          - "Authorization"
                    QueryStringsConfig: {}

