service: product-checker

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    USER_TABLE: productCheckerUsersTable
    PRODUCT_TABLE: productCheckerProductTable
    SUBSCRIPTION_TABLE: productCheckerSubscriptionTable
  httpApi:
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://dev-hw-jobs-integration.eu.auth0.com/
        audience: productchecker
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.USER_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.PRODUCT_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.PRODUCT_TABLE}/index/*"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.SUBSCRIPTION_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.SUBSCRIPTION_TABLE}/index/*"

package:
  patterns:
    - '!frontend/**'

functions:
  # Profile
  getProfileInfo:
    handler: functions/profile.get
    events:
      - httpApi:
            method: GET
            path: /api/profile
            authorizer: serviceAuthorizer
  createProfileInfo:
    handler: functions/profile.post
    events:
      - httpApi:
            method: POST
            path: /api/profile
            authorizer: serviceAuthorizer
  registerProfile:
    handler: functions/register.post
    events:
      - httpApi:
          method: POST
          path: /api/register
          authorizer: serviceAuthorizer
  # Products
  listProducts:
    handler: functions/products.getAll
    events:
      - httpApi:
          method: GET
          path: /api/products
          authorizer: serviceAuthorizer
  # Subscriptions
  subscribe:
    handler: functions/subscriptions.post
    events:
      - httpApi:
          method: POST
          path: /api/subscribe
          authorizer: serviceAuthorizer
  unsubscribe:
    handler: functions/subscriptions.delete
    events:
      - httpApi:
          method: DELETE
          path: /api/unsubscribe
          authorizer: serviceAuthorizer
  listSubscribtions:
    handler: functions/subscriptions.getAllForUser
    events:
      - httpApi:
          method: GET
          path: /api/subscriptions
          authorizer: serviceAuthorizer
  listUsers:
    handler: functions/users.get
    events:
      - httpApi:
          method: GET
          path: /api/users
          authorizer: serviceAuthorizer
  # Provider functions
  refreshIkea:
    handler: functions/providerIKEA.refresh
    events:
      - schedule: rate(1 day)

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    productTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PRODUCT_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: provider
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: providerIndex
            KeySchema:
              - AttributeName: provider
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
    subscriptionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SUBSCRIPTION_TABLE}
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: productId
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
